package com.zaywifi.app;

import android.app.*;import android.os.*;import android.content.*;import android.graphics.Color;import android.view.*;import android.widget.*;import java.io.*;import java.util.*;

public class MainActivity extends Activity {
  private VoucherManager vouchers; private PortalServer portal; private TextView status,gateway,log; private String gw="";
  @Override public void onCreate(Bundle b){super.onCreate(b);setContentView(R.layout.activity_main);vouchers=new VoucherManager(this);portal=new PortalServer(this,vouchers);status=findViewById(R.id.status);gateway=findViewById(R.id.gateway);log=findViewById(R.id.log);findViewById(R.id.start).setOnClickListener(v->startService());findViewById(R.id.stop).setOnClickListener(v->stopService());findViewById(R.id.create).setOnClickListener(v->createDialog());findViewById(R.id.list).setOnClickListener(v->listDialog());findViewById(R.id.clients).setOnClickListener(v->clientsDialog());refreshGateway();}
  private void refreshGateway(){new Thread(()->{String x=detectGateway();runOnUiThread(()->{gw=x;gateway.setText("Gateway: "+(x.isEmpty()?"-":x));});}).start();}
  private String detectGateway(){Root.Result r=Root.run("ip -4 addr show 2>/dev/null");String[] lines=r.output.split("\\n");for(String l:lines){String t=l.trim();if(!t.startsWith("inet "))continue;String ip=t.substring(5).split("/")[0];if(ip.startsWith("192.168.")||ip.startsWith("10.")||ip.startsWith("172."))return ip;}return "";}
  private void startService(){new Thread(()->{gw=detectGateway();if(gw.isEmpty()){ui("Hotspot belum terdeteksi. Aktifkan hotspot Android terlebih dahulu.",false);return;}runOnUiThread(()->gateway.setText("Gateway: "+gw));if(!portal.start()){ui("Port 8080 sedang dipakai.",false);return;}Root.Result f=Firewall.setup(gw,8080);if(!f.ok){portal.stop();ui("Gagal memasang firewall root:\n"+f.output,false);return;}writeEmptyAuth();ui("Voucher mode aktif. Captive portal berjalan di http://"+gw+":8080",true);}).start();}
  private void stopService(){new Thread(()->{Root.Result r=Firewall.cleanup();portal.stop();writeEmptyAuth();ui(r.ok?"Voucher mode dihentikan dan firewall dibersihkan.":"Cleanup selesai dengan catatan: "+r.output,r.ok);}).start();}
  private void writeEmptyAuth(){try{File d=new File(getFilesDir(),"data");d.mkdirs();new FileOutputStream(new File(d,"authorized_ips.txt"),false).close();}catch(Exception ignored){}}
  private void createDialog(){LinearLayout box=new LinearLayout(this);box.setPadding(40,10,40,0);box.setOrientation(LinearLayout.VERTICAL);RadioGroup mode=new RadioGroup(this);RadioButton auto=new RadioButton(this);auto.setId(View.generateViewId());auto.setText("Otomatis (6 karakter)");RadioButton custom=new RadioButton(this);custom.setId(View.generateViewId());custom.setText("Custom");mode.addView(auto);mode.addView(custom);auto.setChecked(true);EditText count=new EditText(this);count.setHint("Jumlah voucher (default 1)");count.setInputType(2);EditText code=new EditText(this);code.setHint("Kode custom");code.setVisibility(View.GONE);mode.setOnCheckedChangeListener((g,id)->code.setVisibility(id==custom.getId()?View.VISIBLE:View.GONE));box.addView(mode);box.addView(count);box.addView(code);new AlertDialog.Builder(this).setTitle("Buat Voucher").setView(box).setPositiveButton("Generate",(d,w)->{if(auto.isChecked()){int n=1;try{n=Math.max(1,Math.min(1000,Integer.parseInt(count.getText().toString().trim())));}catch(Exception ignored){}StringBuilder s=new StringBuilder();for(int i=0;i<n;i++)s.append(vouchers.createAuto()).append(i+1<n?"\n":"");showText("Voucher dibuat",s.toString());}else{try{showText("Voucher dibuat",vouchers.createCustom(code.getText().toString()));}catch(Exception e){toast(e.getMessage());}}}).setNegativeButton("Batal",null).show();}
  private void listDialog(){List<VoucherManager.Voucher> vs=vouchers.list();if(vs.isEmpty()){showText("Daftar Voucher","Belum ada voucher.");return;}LinearLayout box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);for(VoucherManager.Voucher v:vs){LinearLayout row=new LinearLayout(this);row.setPadding(10,12,10,12);row.setOrientation(LinearLayout.HORIZONTAL);TextView t=new TextView(this);t.setText(v.code+"\n"+(v.used()?"Dipakai · "+v.ip:"Belum dipakai"));t.setTextColor(Color.WHITE);t.setTextSize(15);row.addView(t,new LinearLayout.LayoutParams(0,-2,1));Button reset=new Button(this);reset.setText("Reset");reset.setOnClickListener(x->{if(v.used()){Firewall.revoke(v.ip);portal.writeAuth(v.ip,false);}vouchers.reset(v.code);toast("Voucher di-reset");});row.addView(reset);Button del=new Button(this);del.setText("Hapus");del.setOnClickListener(x->{new AlertDialog.Builder(this).setTitle("Hapus voucher?").setMessage(v.code).setNegativeButton("Batal",null).setPositiveButton("Hapus",(d,w)->{if(v.used())Firewall.revoke(v.ip);vouchers.delete(v.code);if(v.used())portal.writeAuth(v.ip,false);toast("Voucher dihapus");}).show();});row.addView(del);box.addView(row);}new AlertDialog.Builder(this).setTitle("Daftar Voucher").setView(box).setPositiveButton("Tutup",null).show();}
  private void clientsDialog(){List<String> cs=portal.clients();if(cs.isEmpty()){showText("Client Aktif","Belum ada client yang diberi akses.");return;}LinearLayout box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);for(String ip:cs){LinearLayout row=new LinearLayout(this);row.setGravity(Gravity.CENTER_VERTICAL);TextView t=new TextView(this);t.setText(ip);t.setTextColor(Color.WHITE);t.setTextSize(16);row.addView(t,new LinearLayout.LayoutParams(0,-2,1));Button cut=new Button(this);cut.setText("Putuskan");cut.setOnClickListener(v->{Firewall.revoke(ip);portal.writeAuth(ip,false);toast("Akses "+ip+" diputuskan");});row.addView(cut);box.addView(row);}new AlertDialog.Builder(this).setTitle("Client Aktif").setView(box).setPositiveButton("Tutup",null).show();}
  private void showText(String title,String text){new AlertDialog.Builder(this).setTitle(title).setMessage(text).setPositiveButton("OK",null).show();}
  private void ui(String s,boolean ok){runOnUiThread(()->{status.setText(ok?"● Hotspot voucher aktif":"● "+s.split("\\n")[0]);status.setTextColor(ok?Color.rgb(56,217,150):Color.rgb(255,113,129));log.setText(s);});}
  private void toast(String s){runOnUiThread(()->Toast.makeText(this,s==null?"Terjadi kesalahan":s,Toast.LENGTH_SHORT).show());}
}
